# Generated by Django 3.2.5 on 2021-07-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_one',
            field=models.CharField(default='mahatma gandhi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
